version: 2
jobs:
  build:
    machine: true
    docker_layer_caching: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t vhanda/flutter-android:latest .
      - run: docker push vhanda/flutter-android:latest
